export const projects = [
  {
    id: 1,
    description:
      "A clean card design with perfect centering and subtle shadows.",
    tags: ["HTML", "CSS"],
    image: "https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    liveUrl: "#",
    codeUrl: "#",
    difficulty: "Newbie",
  },
  {
    id: 1,
    title: "QR Code Component",
    description:
      "A clean card design with perfect centering and subtle shadows.",
    tags: ["HTML", "CSS"],
    image: "https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    liveUrl: "#",
    codeUrl: "#",
    difficulty: "Newbie",
  },
  {
    id: 2,
    title: "Order Summary Component",
    description:
      "Modern payment interface with hover states and responsive design.",
    tags: ["HTML", "CSS", "Flexbox"],
    image: "/api/placeholder/600/400",
    liveUrl: "#",
    codeUrl: "#",
    difficulty: "Newbie",
  },
  {
    id: 3,
    title: "Interactive Rating Component",
    description: "User feedback system with state management and animations.",
    tags: ["HTML", "CSS", "JavaScript"],
    image: "/api/placeholder/600/400",
    liveUrl: "#",
    codeUrl: "#",
    difficulty: "Junior",
  },
  {
    id: 4,
    title: "Tip Calculator App",
    description:
      "Real-time calculation tool with validation and responsive UI.",
    tags: ["HTML", "CSS", "JavaScript", "React"],
    image: "/api/placeholder/600/400",
    liveUrl: "#",
    codeUrl: "#",
    difficulty: "Intermediate",
  },
  {
    id: 5,
    title: "Space Tourism Website",
    description: "Multi-page website with complex layouts and dynamic content.",
    tags: ["HTML", "CSS", "JavaScript", "React", "React Router"],
    image: "/api/placeholder/600/400",
    liveUrl: "#",
    codeUrl: "#",
    difficulty: "Advanced",
  },
  {
    id: 6,
    title: "REST Countries API",
    description: "Data visualization with API integration and theme switching.",
    tags: ["HTML", "CSS", "JavaScript", "React", "API"],
    image: "/api/placeholder/600/400",
    liveUrl: "#",
    codeUrl: "#",
    difficulty: "Advanced",
  },
  {
    id: 7,
    title: "Conference Ticket enerator",
    description: "A responsive and accessible conference ticket generator with full form validation, keyboard navigation, screen reader support, and dynamic ticket display.",
    tags: ["Vite", "React", "TailwindCSS"],
    image: "/conference-ticket-generator.png",
    liveUrl: "https://arilab-conference-ticket-generator.vercel.app/",
    codeUrl: "#",
    difficulty: "Junior",
  },
  
];